version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ../backend:/var/www/html/backend
      - ../frontend:/var/www/html/frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_databases
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
